apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: gke-maintenance-exclusion-job
  labels:
    cloud.googleapis.com/location: asia-southeast1 # Make sure this matches your CLOUD_RUN_JOB_REGION
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - name: gke-updater
              image: asia-docker.pkg.dev/euprdstage1/eup/eup-gke-maintenance-updater:latest # VERIFY THIS PATH CAREFULLY
              env:
                - name: GKE_CLUSTER_NAME
                  value: "id-stage2-standard-cluster" # REQUIRED: Replace with your GKE cluster name
                - name: GKE_CLUSTER_REGION
                  value: "asia-east1" # REQUIRED: Replace with your GKE cluster region (e.g., asia-southeast1)
                - name: PROJECT_ID
                  value: "eupfin-internal01" # IMPORTANT: This is the GKE cluster's project ID
                - name: EXCLUSION_NAME
                  value: "cloud-run-scheduled-exclusion" # REQUIRED: A descriptive name for the exclusion
          serviceAccountName: jenkins@euprdstage1.iam.gserviceaccount.com # IMPORTANT: This is the Cloud Run Job's service account email