apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: gke-maintenance-exclusion-id-stage2-standard-cluster
  labels:
    cloud.googleapis.com/location: asia-southeast1
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - name: gke-updater
              image: asia-docker.pkg.dev/euprdstage1/eup/eup-gke-maintenance-updater:latest
              env:
                - name: GKE_CLUSTER_NAME
                  value: "id-stage2-standard-cluster"
                - name: GKE_CLUSTER_REGION
                  value: "asia-east1"
                - name: PROJECT_ID
                  value: "eupfin-internal01"
                - name: EXCLUSION_NAME
                  value: "cloud-run-scheduled-exclusion-id-stage2"
          serviceAccountName: jenkins@euprdstage1.iam.gserviceaccount.com
